package exceptionHandling;

public class FinnallyBlock {

	public static void main(String[] args) {
		
		try
		{
			System.out.println("hi");
		int a = 9/0;
		}
		catch (ArithmeticException e) {
			System.out.println("hello");
			e.printStackTrace();
		}
		finally {
			System.out.println("I'm finally block ");
		}
	}

}
